name: fakestore
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.6.2


dependencies:
  flutter:
    sdk: flutter

  # animation
  rive: ^0.13.4

  # code generation
  freezed_annotation: ^2.4.4

  image_editor: ^1.4.0

  # ui
  flutter_svg: ^2.0.5
  mask_text_input_formatter: ^2.4.0
  event_bus: ^2.0.0

  # local storage
  shared_preferences: ^2.0.15
  objectbox: ^4.1.0
  objectbox_flutter_libs: ^4.1.0

  # logger
  logger: ^2.0.1

  # network
  cached_network_image: ^3.3.0
  url_launcher: ^6.1.11
  http: ^1.1.0
  retrofit: ^4.0.1
  dio: ^5.3.2
  pretty_dio_logger: ^1.3.1

  # data format
  json_annotation: ^4.7.0
  uuid: ^4.5.1
  provider: ^6.0.4
  intl: ^0.19.0
  equatable: ^2.0.5
  collection: ^1.18.0

  # streams
  rxdart: ^0.28.0

  # micro-frameworks
  get: ^4.6.5
  dartz: ^0.10.1

  # state management
  flutter_bloc: ^9.1.1

  # platform
  cupertino_icons: ^1.0.2
  package_info_plus: ^8.3.0

  # dependency injection
  kiwi: ^5.0.1

  # localization:
  slang: ^4.7.1
  slang_flutter: ^4.7.0
  flutter_localizations:
    sdk: flutter
  auto_size_text: ^3.0.0

  infinite_scroll_pagination: ^4.0.0

dev_dependencies:
  # code generation
  freezed: ^2.5.7
  retrofit_generator: ^9.2.0
  build_runner: ^2.4.15
  json_serializable: ^6.5.4
  objectbox_generator: ^4.1.0

  # analyzer
  flutter_lints: ^5.0.0

  # dependency injection
  kiwi_generator: ^4.1.0

  # test
  flutter_test:
    sdk: flutter

  # localization
  slang_build_runner: ^4.7.0

  # config
  flutter_launcher_icons: ^0.14.3

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/images/
    - assets/icons/
    - assets/fonts/

  fonts:
    - family: Urbanist
      fonts:
        - asset: assets/fonts/Urbanist-Black.ttf
        - asset: assets/fonts/Urbanist-Bold.ttf
        - asset: assets/fonts/Urbanist-ExtraBold.ttf
        - asset: assets/fonts/Urbanist-ExtraLight.ttf
        - asset: assets/fonts/Urbanist-Light.ttf
        - asset: assets/fonts/Urbanist-Medium.ttf
        - asset: assets/fonts/Urbanist-Regular.ttf
        - asset: assets/fonts/Urbanist-SemiBold.ttf
        - asset: assets/fonts/Urbanist-Thin.ttf

objectbox:
  output_dir: app/data/datasources/local/object_box/